apiVersion: apps/v1
kind: Deployment
metadata:
  name: front
  namespace: esb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
    spec:
      containers:
        - name: front
          image: registry.tritux.com/easybulk3/front:v4.6.1
          ports:
            - containerPort: 80
          #resources:   
          #  requests:
          #    cpu: "100m"
          #    memory: "128Mi"
          #  limits:
          #    cpu: "500m"
          #    memory: "256Mi"
          #readinessProbe:  # Only send traffic to ready pods
          #  httpGet:
          #    path: /
          #    port: 80
          #  initialDelaySeconds: 5
          #  periodSeconds: 10
          #  timeoutSeconds: 2
          #  failureThreshold: 3
          #livenessProbe:   
          #  httpGet:
          #    path: /
          #    port: 80
          #  initialDelaySeconds: 10
          #  periodSeconds: 30
          #  timeoutSeconds: 3
          #  failureThreshold: 3
      imagePullSecrets:
        - name: docker-registry-secret
