apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-auth
  namespace: esb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-auth
  template:
    metadata:
      labels:
        app: keycloak-auth
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: auth
          image: registry.tritux.com/easybulk3/keycloak:v4.1.4
          args: 
          - "start"
          #- "--features=docker,token-exchange"
          - "--http-relative-path=/auth"  
          - "--spi-theme-cache-themes=false" 
          - "--spi-theme-cache-templates=false"
          - "--import-realm"
          #- "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true"
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: keycloak-auth
            - secretRef:
                name: keycloak-secret
          #env:
          #  - name: KC_BOOTSTRAP_ADMIN_USERNAME 
          #    value: "ebs-superadmin"
          #  - name: KC_BOOTSTRAP_ADMIN_PASSWORD
          #    value: "admin"
    
          volumeMounts:
            - name: realm-config
              mountPath: /opt/keycloak/data/import/ebs-realm-realm.json
              subPath: ebs-realm.json
          # --- Resource Requests and Limits (+100 users considr increasing memory to 4-8Gi and CPU to 2+ cores.)  ---
          #resources:
          #  requests:
          #    memory: "1Gi"
          #    cpu: "500m"
          #  limits:
          #    memory: "2Gi"
          #    cpu: "1"
      volumes:
        - name: realm-config
          configMap:
            name: keycloak-realm


