apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pv-cleanup-role
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pv-cleanup-binding
subjects:
- kind: ServiceAccount
  name: pv-cleanup-sa
  namespace: esb
roleRef:
  kind: ClusterRole
  name: pv-cleanup-role
  apiGroup: rbac.authorization.k8s.io

