apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: esb
spec:
  type: NodePort
  selector:
    postgres-operator.crunchydata.com/cluster: postgres
  ports:
    - port: 5432
      targetPort: postgres
      nodePort: 30007

